/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32 VS Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "platform_definitions.h"
#include "stm32f4xx.h"

#include <stdint.h>
#include <stdio.h>

#include "i2s.h"
#include "clock.h"
#include "uart.h"
#include "dma.h"
#include "dbg_pin.h"

static uint16_t dma_global_buffer = 0;
static volatile uint32_t register_val = 0;
static volatile uint16_t register_val_dr = 0;

int main(void)
{
    discovery_clock_100mhz_config();
    uart2_tx_init();
    register_val = (DMA1->LISR & DMA_LISR_DMEIF3);
    printf("uart and clock configured\r\n");
    i2s_init(INTERRUPTS_NOT_USED);
    dma_init(&dma_global_buffer);

    configure_debug_pin();
    /* Loop forever */
	for(;;)
    {
        printf("dupsko\r\n");
        for(int i = 0; i < 1000000; i++){}
    }
}
